### ISSUE TITLE
TourModule Blocks rendering

### ISSUE THREAD

**Issue by rjwismar** [isaacplmann/ngx-tour#123]
In my case I have a shared module that generate a list and make some options available, like a checkbox to select entries. That is implement in a lazy loaded module. The TourModule works fine if I only add this to the lazy load module, if I implement the TourModule in the shared module the entries won't be rendered. I must take some clicks or scroll the window to render the full page. 

<img width="571" alt="renderproblem" src="https://user-images.githubusercontent.com/41587762/43089662-89a0a62a-8ea5-11e8-9d33-e59c341aa682.png">

After scrolling all Elements looks like the first you see.

Have anybody a suggestion which problem is going on.
Versions 
ngx-tour: 2.0.0
Angular: 5.2.11

**Comment by isaacplmann** [comment]
What happens if you comment the `TourModule` code out of your app completely?

I have a suspicion that your code was depending on one of the `ngx-tour` directives to fire change detection for you and when it was removed your component doesn't see the changes.

Try adding this code in your component:
```
export class MyComponent implements OnInit {
  constructor(private changeDetectorRef: ChangeDetectorRef) {}
  ngOnInit() {
    setTimeout(() => this.changeDetectorRef.detectChanges());
  }
}
```
