### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import  - popover.js

### ISSUE THREAD

**Issue by hsbalar** [isaacplmann/ngx-tour#13]
Giving an error while importing TourNgBootstrapModule.root() in app.module.ts.
I simply install ng2-tour and hotkey module and import to app.module.
`Its giving from @ng-bootstrap/ng-bootstrap/popover/popover.js`

**Comment by isaacplmann** [comment]
Are you using angular 4.x? I haven't tested that yet.

Also are you importing ng-bootstrap? That's a peer dependency.

On Apr 7, 2017 3:14 AM, "Hitesh" <notifications@github.com> wrote:

Giving an error while importing TourNgBootstrapModule.root() in
app.module.ts

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/isaacplmann/ng2-tour/issues/13>, or mute the thread

**Comment by hsbalar** [comment]
I'm using angular 2.4.x. Yes i'm importing ng-bootstrap
I have used webpack build tool

**Comment by isaacplmann** [comment]
I just set up a simple test app, and I don't actually need to import ng-bootstrap explicitly.  What version of ng-bootstrap did you import?  Maybe there's a conflict.
