### ISSUE TITLE
Placement in MdMenu

### ISSUE THREAD

**Issue by pranavjain** [isaacplmann/ngx-tour#130]
Hi,
I am using MdMenu library as I don't prefer importing bootstrap into my project as of now. I need to place the tour step on the right side of my div but 'placement' attribute is currently ignored by MdMenu.

Why is the library ignoring it? Is there some way to overwrite it?

**Comment by hakimio** [comment]
Hi,
Basically, the reason why it's not supported is because Angular Material [mat-menu](https://material.angular.io/components/menu/api) doesn't provide this kind of positioning API. If you don't believe me, you can try to play with [this example app](https://stackblitz.com/edit/angular-i6sg2w?file=app/menu-overview-example.html) yourself.

If this functionality is a must have for you, as a workaround you could create a zero width and height div at the position where you want your tour step's top left corner to be, and attach the tour step to that div.

**Comment by isaacplmann** [comment]
Thanks for jumping in, @hakimio

**Comment by pranavjain** [comment]
Thanks for the insights!
