### ISSUE TITLE
Any plans for angular 9 upgrade?

### ISSUE THREAD

**Issue by pnaika** [isaacplmann/ngx-tour#195]
Thank you for this amazing lib, any plans to upgrade the project to angular 9. Thanks

**Comment by isaacplmann** [comment]
Are there any actual errors when trying the library in an Angular 9 app?  The recommendation from the Angular team is to keep  libraries compiled with the View Engine renderer until Angular 10.

I think all that is needed is to bump the peerDependency requirements in the app to not throw a warning during `npm install`.

Please post any actual errors you run into when upgrading.

**Comment by bartromgens** [comment]
I get the following error when upgrading and building the first time:

> Error: Failed to compile entry-point ngx-tour-core (module as esm5) due to compilation errors:
node_modules/@angular/common/common.d.ts:115:22 - error NG6002: Appears in the NgModule.imports of TourModule, but could not be resolved to an NgModule class.

>This likely means that the library (@angular/common) which declares CommonModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by brunin2509** [comment]
After building a library that is using Angular v9 in production mode, when trying to start an application that depends on this library, I am getting the following error:

```
ERROR in ./lib/lacuna-spa/__ivy_ngcc__/fesm2015/lacuna-spa.js 7880:108-131
"export 'NgxmTourService' (imported as 'ɵngcc25') was not found in 'ngx-tour-md-menu'
```

This error only happens when my library is using Angular v9 (it does not happen in versions 7 and 8). Apparently, Angular v9 transforms the reference to "TourService" from 'ngx-tour-md-menu' to NgxmTourService again, even though this service is exported as TourService in public_api.ts, and, because of that, it cannot resolve this reference again when compiling/starting the application.
