### ISSUE TITLE
Angular 5?

### ISSUE THREAD

**Issue by raymondtri** [isaacplmann/ngx-tour#60]
I'm getting some weird dependency issues after attempting to build with angular 5.

![image](https://user-images.githubusercontent.com/14185938/32912022-dbd93008-cadb-11e7-8c03-f9e3666a1665.png)

If you take a look at those dependency issues, then my package.json
`    "@angular/animations": "^5.0.1",
    "@angular/cdk": "^5.0.0-rc0",
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/compiler-cli": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/material": "^5.0.0-rc0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",`
The only @angular package missing is the router. So why is it throwing dependency errors for animations, cdk, material, core, common, and http?

Is this not updated to angular 5 yet?

**Comment by isaacplmann** [comment]
It should support Angular 5. But the cdk needs to be 2.0.0-beta.12

**Comment by raymondtri** [comment]
Can I ask why it is throwing dependency errors and expecting ~4.2.5, and 4.3.0? The dependencies on the home page are listed as out-of-date as well. I can try setting the cdk package to 2.0.0-beta.12, do you think that will fix all of the other dependency errors?

Thanks,
Ray

**Comment by isaacplmann** [comment]
I'll not sure. I'm on vacation until Monday. I'll give you a better answer
then.

On Nov 17, 2017 8:51 AM, "Ray Tri" <notifications@github.com> wrote:

Can I ask why it is throwing dependency errors and expecting ~4.2.5, and
4.3.0? The dependencies on the home page are listed as out-of-date as well.
I can try setting the cdk package to 2.0.0-beta.12, do you think that will
fix all of the other dependency errors?

Thanks,
Ray

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/isaacplmann/ngx-tour/issues/60#issuecomment-345264286>,
or mute the thread

**Comment by isaacplmann** [comment]
It looks like I need to update the peer dependencies on all the ngx-tour modules.  I plan to work on that tomorrow.

**Comment by raymondtri** [comment]
Thanks man, much appreciated.

**Comment by isaacplmann** [comment]
So it wasn't the day I planned, but I've released a new version that won't throw peerDependency warnings.  Try ngx-tour-md-menu@2.0.0-rc.2
