### ISSUE TITLE
Hyperlink in content text

### ISSUE THREAD

**Issue by magar91** [isaacplmann/ngx-tour#72]
Hello
Is there a way to add a hyperlink to the content text?

**Comment by isaacplmann** [comment]
Not directly.  I should add a feature where you can provide a `string` or a `templateRef` for the `content` of each step.  That would solve this issue and let people put whatever other components they want inside the step.

The best you can do right now is copy the default `<tour-step-template>` and replace `{{step?.content}}` with this:

```
<ng-template *ngIf="step?.template else defaultContentTemplate" [ngTemplateOutlet]="step?.template" [ngTemplateOutletContext]="{ $implicit: step }"></ng-template>
<ng-template #defaultContentTemplate>{{step?.content}}</ng-template>
```

Then you can add a `template` property to your steps with a reference to a `TemplateRef` and that will be used instead of the `content` property.

This is probably how I will implement this feature when I get around to it.

**Comment by magar91** [comment]
Thanks for your quick response @isaacplmann  that does help me, but I think I didn't explain myself very clearly, I'm sorry for that. 
what I meant is to add a hyperlink like `<a></a>` tag in the context text so that you could redirect to another webpage by clicking the text, not another component of the app

**Comment by isaacplmann** [comment]
Someone asked for me to explain this in more detail:

> Then you can add a template property to your steps with a reference to a TemplateRef and that will be used instead of the content property.

In whatever component that you use to initialize your tour steps, add a template to the html:

```html
<ng-template #stepTemplate let-step="step">
  <strong>html</strong> tags will work here. <br>
  You can also use info from the step:  {{step.content}}
</ng-template>
```

Then in your ts file, get a reference to that template like this:

```ts
@ViewChild('stepTemplate') stepTemplate: TemplateRef;
```

And use it in your tour step definition like this:
```ts
this.tourService.initialize([
  {
  anchorId: 'some.anchor.id',
  content: 'Some content',
  title: 'First',
}, {
  anchorId: 'another.anchor.id',
  content: 'Other content',
  template: this.stepTemplate,
  title: 'Second',
  },
]);
```

The first step will display the string content like normal, the second step will use a custom template.
