### ISSUE TITLE
Is it support ionic3 app

### ISSUE THREAD

**Issue by sandeeppatel344** [isaacplmann/ngx-tour#73]
i am trying to integrate this functionality but its give me error for routing

**Comment by isaacplmann** [comment]
I'll need more information than that if you want me to help you.

On Jan 11, 2018 12:27 AM, "sandeepv2stech" <notifications@github.com> wrote:

i am trying to integrate this functionality but its give me error for
routing

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/isaacplmann/ngx-tour/issues/73>, or mute the thread

**Comment by isaacplmann** [comment]
@TreatDarren thanks for providing some clarity.  Yes, the library is pretty tied to the angular router right now.  However there are only a handful of places that use the router - all in `ngx-tour-core/src/tour.service.ts`.  I'd be open to a PR that abstracts that dependency away so that people could provide their own router logic.  Any router implementation would need to provide two things: (1) a way for the tour service to know when the router is navigating to a new route and (2) a way to tell the router to go to a specific route and be notified when that route is loaded.

**Comment by isaacplmann** [comment]
I'm happy to coach anyone who wants to try their hand at the PR.
