### ISSUE TITLE
Using ngx-tour with Angular 2

### ISSUE THREAD

**Issue by chubbard** [isaacplmann/ngx-tour#74]
I have an angular 2 app and I'd like to use ngx-tour so I did the following:

`npm install ngx-tour-ngx-bootstrap ngx-bootstrap`

But the dependencies require Angular 5.  This is what I got back:

```
+-- UNMET PEER DEPENDENCY ngx-bootstrap@1.9.3
`-- ngx-tour-ngx-bootstrap@2.0.0-beta.9
  +-- UNMET PEER DEPENDENCY @angular/common@^5.0.3
  +-- UNMET PEER DEPENDENCY @angular/core@^5.0.3
  +-- UNMET PEER DEPENDENCY @angular/router@^5.0.3
  +-- ngx-tour-core@2.0.0
  +-- withinviewport@2.0.0
  `-- UNMET PEER DEPENDENCY zone.js@^0.8.18

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN ngx-tour-ngx-bootstrap@2.0.0-beta.9 requires a peer of ngx-bootstrap@^2.0.0-beta.9 but none was installed.
npm WARN ngx-tour-core@2.0.0 requires a peer of @angular/common@^5.0.3 but none was installed.
npm WARN ngx-tour-core@2.0.0 requires a peer of @angular/core@^5.0.3 but none was installed.
npm WARN ngx-tour-core@2.0.0 requires a peer of @angular/router@^5.0.3 but none was installed.
npm WARN ngx-tour-core@2.0.0 requires a peer of zone.js@^0.8.18 but none was installed.
```
Can this work on Angular 2 as the docs describe?

**Comment by isaacplmann** [comment]
Try `ngx-tour-ngx-bootstrap@1.0.4`.  And make sure the version of `ngx-bootstrap` that you install is compatible with your old version of Angular too.

What's blocking you from upgrading to the latest Angular?  There aren't very many differences between 2.x and 5.x.

**Comment by jlherren** [comment]
The website advertises *"Product tour using Angular (2+)"*. So that definitely needs to be updated if Angular 2 isn't supported anymore by the latest version.

Our application is built with Angular 4.4 but ngx-tour-md-menu seems to insist on Angular 5 (which by the way was released only 4 months ago!). We cannot upgrade to Angular 5 because we would have to rewrite quite a few classes due to the removal of deprecated features. I suppose upgrading from Angular 2.x would be even more difficult.
